forge "https://forgeapi.puppetlabs.com"

mod 'puppet-archive', '7.0.0'
mod 'puppet-epel', '4.1.0'
mod 'puppetlabs-concat', '9.0.0'
mod 'puppetlabs-aws', '2.1.0'
mod 'puppetlabs-docker', '7.0.0'
mod 'puppetlabs-apache', '10.1.0'
mod 'puppetlabs-mysql', '15.0.0'
mod 'puppetlabs-stdlib', '9.1.0'
